export const prompts = {
  0: "A whale breaching the ocean surface",
  1: "A roller coaster plummeting down a steep track",
  2: "A kangaroo bounding across the outback",
  3: "A rocket launching into space",
  4: "A phoenix rising from ashes",
  5: "A fire ant army marching",
  6: "A horse leaping a wooden fence",
  7: "A deer leaping over a fallen log",
  8: "A cheetah sprinting across the savannah",
  9: "A scateboarder grinding a rail",
  10: "A tornado spinning wildly across a plain",
  11: "A spaceship entering hyperspace",
  12: "A snake striking at prey",
  13: "A surfer riding a massive wave",
  14: "A spider weaving a web swiftly",
  15: "A boxer throwing a powerful punch",
  16: "A mantis shrimp striking with lightning speed",
  17: "A waterfall crashing down a cliff",
  18: "A squirrel leaping from tree to tree",
  19: "A dragonfly zipping over a pond",
  20: "A race car zooming on a track",
  21: "A hammer striking a nail",
  22: "A firework exploding in the sky",
  23: "A lightning bolt striking a tree",
  24: "A wolf pack running through snow",
  25: "A dolphin leaping through waves",
  26: "A python constricting its prey",
  27: "A falcon catching prey mid-flight",
  28: "A volcano sending ash into the sky",
  29: "A jet ski speeding across a lake",
  30: "A pelican diving for fish",
  31: "A stallion rearing up and kicking",
  32: "A jet plane banking sharply",
  33: "A catapult launching a projectile",
  34: "A jellyfish pulsating gracefully in water",
  35: "A geyser erupting hot water into the air",
  36: "A hummingbird darting between flowers",
  37: "A squirrel darting between tree branches",
  38: "A car drifting on a wet road",
  39: "A hummingbird flicking its wings rapidly",
  40: "A dragon breathing fire",
  41: "A spider leaping to catch a fly",
  42: "A spacecraft landing on Mars",
  43: "A spaceship launching a probe",
  44: "A speedboat racing across water",
  45: "A cheetah twisting mid-run",
  46: "A rocket booster separating mid-flight",
  47: "A bumblebee buzzing between flowers",
  48: "A snowboarder jumping off a ramp",
  49: "A bison charging across the plains",
  50: "A waterwheel turning in a river",
  51: "A rocket landing vertically on a platform",
  52: "A sea turtle swimming powerfully through waves",
  53: "A mountain biker flying over a jump",
  54: "A racehorse thundering down a track",
  55: "A hawk diving towards the ground",
  56: "A cobra flaring its hood",
  57: "A horse rearing up wildly",
  58: "A scorpion snapping its claws",
  59: "A volcano erupting molten lava",
  60: "A dragonfly skimming over water",
  61: "A fire spreading quickly through a forest",
  62: "A mountain goat scaling a steep cliff",
  63: "A tornado swirling dust and debris",
  64: "A whale spouting water from its blowhole",
  65: "A falcon chasing a pigeon",
  66: "A hummingbird hovering rapidly",
  67: "A submarine surfacing rapidly",
  68: "A comet streaking across the night sky",
  69: "A butterfly fluttering among flowers",
  70: "A wind turbine spinning in strong gusts",
  71: "A parrot flapping its colorful wings",
  72: "A drone zipping through a forest",
  73: "A submarine launching a missile",
  74: "A lightning storm illuminating the sky",
  75: "A racecar making a tight turn",
  76: "A skier carving through fresh powder",
  77: "A lioness pouncing on prey",
  78: "A submarine diving deep underwater",
  79: "A snow leopard sprinting up a rocky slope",
  80: "A waterfall cascading into a pool",
  81: "A shark breaching to catch a seal",
  82: "A rocket sled speeding along a track",
  83: "A fighter jet breaking the sound barrier",
  84: "A hawk flapping its wings powerfully",
  85: "A river rapidly flooding a valley",
  86: "A whale tail slapping the ocean surface",
  87: "A glacier calving into the sea",
  88: "A tornado lifting debris into the air",
  89: "A gazelle bounding over the grasslands",
  90: "A storm cloud swirling violently",
  91: "A thunderstorm rolling over mountains",
  92: "A tornado touching down in a field",
  93: "A comet blazing through space",
  94: "A condor soaring over mountains",
  95: "A surfer cutting sharply on a wave",
  96: "A caterpillar transforming into a butterfly",
  97: "A horse sprinting across a beach",
  98: "A glacier moving slowly but powerfully",
  99: "A spider scuttling quickly across leaves",
  100: "A glider soaring silently in the sky",
  101: "A meteor blazing through the atmosphere",
  102: "A panther stalking silently through the jungle",
  103: "A helicopter lifting off from a helipad",
  104: "A lava flow creeping down a mountainside",
  105: "A peregrine falcon swooping toward the ground",
  106: "A boxer dodging a punch and countering in slow motion",
  107: "A sprinter exploding out of the starting blocks",
  108: "A marathon runner pushing through exhaustion",
  109: "A track runner crossing the finish line in victory",
  110: "A rock climber hanging by one hand on a cliff face",
  111: "A breakdancer spinning on their head under neon lights",
  112: "A martial artist delivering a flying kick midair",
};
